version: '3'

services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    depends_on:
      - redis
    volumes:
      - .:/app

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6380:6379"

  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A celery_worker.celery worker --loglevel=info --concurrency=4
    depends_on:
      - redis
    volumes:
      - .:/app
